import {prospects} from './src/data.js';
import {enrichProspects,csvFor} from './src/qualification.js';
const rows=enrichProspects(prospects);const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const owners=[...new Set(rows.map(r=>r.owner))].sort();for(const o of owners){const x=document.createElement('option');x.textContent=o;$('owner').append(x)}
function visible(){const q=$('search').value.trim().toLowerCase(),s=$('status').value,o=$('owner').value;return rows.filter(r=>(s==='all'||r.qualification.status===s)&&(o==='all'||r.owner===o)&&(!q||[r.prospect,r.owner,r.next_step,r.qualification.reason].join(' ').toLowerCase().includes(q)))}
function detail(r){$('detail').innerHTML=`<h2>${esc(r.prospect)}</h2><div class="detail-grid"><div><h3>Decision</h3><p><span class="badge">${esc(r.qualification.status)}</span></p><p>${esc(r.qualification.reason)}</p><p><strong>Next step:</strong> ${esc(r.next_step)}</p></div><div><h3>Evidence</h3><ul><li>Fit: ${esc(r.fit)}</li><li>Need: ${esc(r.need)}</li><li>Timing: ${esc(r.timing)}</li><li>Next step present: ${r.next_step?.trim()?'yes':'no'}</li></ul><p><small>${esc(r.source)}</small></p></div></div>`}
function render(){const v=visible();$('qualifiedCount').textContent=rows.filter(r=>r.qualification.status==='QUALIFIED').length;$('reviewCount').textContent=rows.filter(r=>r.qualification.status==='REVIEW').length;$('disqualifiedCount').textContent=rows.filter(r=>r.qualification.status==='DISQUALIFIED').length;$('resultCount').textContent=`${v.length} of ${rows.length} prospects`;$('empty').hidden=v.length!==0;$('pipeline').innerHTML='';for(const r of v){const tr=document.createElement('tr');tr.tabIndex=0;tr.innerHTML=`<td>${esc(r.prospect)}</td><td>${esc(r.owner)}</td><td>${esc(r.fit)}</td><td>${esc(r.need)}</td><td>${esc(r.timing)}</td><td><span class="badge">${esc(r.qualification.status)}</span></td><td>${esc(r.next_step)}</td>`;tr.onclick=()=>detail(r);tr.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();detail(r)}};$('pipeline').append(tr)}}
for(const id of ['search','status','owner']) $(id).addEventListener('input',render);
$('export').onclick=()=>{const blob=new Blob([csvFor(visible())],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='day11-prospect-qualification.csv';a.click();URL.revokeObjectURL(a.href);$('notice').textContent='CSV export prepared from the current filtered view.'};render();
